spring:
  datasource:
    # By default, the database name is randomly generated.
    # But that we want to have jdbc url like this for h2 connection:
    # jdbc:h2:mem:tacocloud
    url: jdbc:h2:mem:tacocloud
    username: sa  # Default username for H2
    password:     # Default password for H2 (leave empty for no password)
  sql:
    init:
      # Ensures schema.sql always runs
      # when schema.sql is changed please: mvn clean install; and then:
      # ./mvnw spring-boot:run
      mode: always
  jpa:
    properties:
      hibernate:
        # Format SQL queries for readability
        format_sql: true
  thymeleaf:
    cache: false
#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace