spring:
  datasource:
    # By default, the database name is randomly generated.
    # But that we want to have jdbc url like this for h2 connection:
    # jdbc:h2:mem:tacocloud
    url: jdbc:h2:mem:tacocloud
    username: sa  # Default username for H2
    password:     # Default password for H2 (leave empty for no password)
  sql:
    init:
      mode: always  # Ensure SQL scripts are always run